JNG-3324: osgi-configuration-mapper
BlackBeltTechnology/osgi-configuration-mapper pull request #9
Opened 2022-03-10 10:56 UTC by kristofkakuszi

2022-03-10 11:46 UTC, noherczeg approved these changes

2022-03-10 12:07 UTC, robertcsakany requested changes

2022-03-10 12:07 UTC, robertcsakany commented on pom.xml
> +    <version>${revision}</version>
The revision property definition is missing. Please define in properties.

2022-03-16 11:43 UTC, noherczeg approved these changes

2022-03-24 22:31 UTC, closed without merging